version: "3.9"

services:
  backend:
    build:
      context: ./backend
      dockerfile: dockerfile
    volumes:
      - ./backend/:/app/:rw
    expose:
      - 80
    networks:
      - net
    depends_on:
      - mysql
    env_file:
      - ./backend/.env.dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 512M

  mysql:
    build:
      context: ./mysql
      dockerfile: dockerfile
    restart: always
    volumes:
      - ./mysql/data:/var/lib/mysql
    expose:
      - 3306
    networks:
      - net
    env_file:
      - ./mysql/.env.dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2g
        reservations:
          cpus: '0.25'
          memory: 1g
  
  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - "8001:80"
    links:
      - mysql
    depends_on:
      - mysql
    networks:
      - net
    env_file:
      - ./mysql/.env.dev
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 512M

  nginx:
    build:
      context: ./nginx
      dockerfile: dockerfile
    restart: always
    ports:
      - "8000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/certs/:/etc/nginx/certs
      - ./nginx/html:/usr/share/nginx/html
      - ./nginx/log/:/var/log/nginx
    depends_on:
      - backend
    networks:
      - net
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1g
        reservations:
          cpus: '0.25'
          memory: 512M

  redis:
    build:
      context: ./redis
      dockerfile: dockerfile
    restart: always
    env_file:
      - ./redis/.env.dev
    networks:
      - net
    expose:
      - 6379
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 2g
        reservations:
          cpus: '0.25'
          memory: 1g

networks:
  net: